#!/bin/bash
shopt -s globstar nullglob nocaseglob
for file in **/*.gif; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file" .gif)
        echo "$filename"
    fi
done | LC_ALL=C sort | tr '\n' '\0' | xargs -0 -n 1 echo
echo

