#!/bin/bash
echo "root:x:0:0:root:/root:/usr/bin/zsh
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
systemd-network:x:101:102:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
systemd-resolve:x:102:103:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
mysql:x:103:110:MySQL Server,,,:/nonexistent:/bin/false
tss:x:104:111:TPM software stack,,,:/var/lib/tpm:/bin/false
strongswan:x:105:65534::/var/lib/strongswan:/usr/sbin/nologin
systemd-timesync:x:106:112:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
redsocks:x:107:113::/var/run/redsocks:/usr/sbin/nologin
rwhod:x:108:65534::/var/spool/rwho:/usr/sbin/nologin
iodine:x:109:65534::/run/iodine:/usr/sbin/nologin
messagebus:x:110:114::/nonexistent:/usr/sbin/nologin
miredo:x:111:65534::/var/run/miredo:/usr/sbin/nologin
tcpdump:x:112:120::/nonexistent:/usr/sbin/nologin
sshd:x:113:65534::/run/sshd:/usr/sbin/nologin
_rpc:x:114:65534::/run/rpcbind:/usr/sbin/nologin
dnsmasq:x:115:65534:dnsmasq,,,:/var/lib/misc:/usr/sbin/nologin
statd:x:116:65534::/var/lib/nfs:/usr/sbin/nologin
avahi:x:117:123:Avahi mDNS daemon,,,:/run/avahi-daemon:/usr/sbin/nologin
stunnel4:x:999:999:stunnel service system account:/var/run/stunnel4:/usr/sbin/nologin
rtkit:x:118:124:RealtimeKit,,,:/proc:/usr/sbin/nologin
Debian-snmp:x:119:125::/var/lib/snmp:/bin/false
speech-dispatcher:x:120:29:Speech Dispatcher,,,:/run/speech-dispatcher:/bin/false
sslh:x:121:127::/nonexistent:/usr/sbin/nologin
postgres:x:122:129:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
nm-openvpn:x:123:130:NetworkManager OpenVPN,,,:/var/lib/openvpn/chroot:/usr/sbin/nologin
inetsim:x:124:132::/var/lib/inetsim:/usr/sbin/nologin
geoclue:x:125:133::/var/lib/geoclue:/usr/sbin/nologin
nm-openconnect:x:126:134:NetworkManager OpenConnect plugin,,,:/var/lib/NetworkManager:/usr/sbin/nologin
lightdm:x:127:135:Light Display Manager:/var/lib/lightdm:/bin/false
sddm:x:128:136:Simple Desktop Display Manager:/var/lib/sddm:/bin/false
pulse:x:129:137:PulseAudio daemon,,,:/run/pulse:/usr/sbin/nologin
saned:x:130:140::/var/lib/saned:/usr/sbin/nologin
colord:x:131:141:colord colour management daemon,,,:/var/lib/colord:/usr/sbin/nologin
king-phisher:x:132:142::/var/lib/king-phisher:/usr/sbin/nologin
Debian-gdm:x:133:143:Gnome Display Manager:/var/lib/gdm3:/bin/false
cyberhacker:x:1000:1000:HAKIZIMANA Yves,,,:/home/cyberhacker:/usr/bin/zsh
mongodb:x:134:65534::/nonexistent:/usr/sbin/nologin
uuidd:x:135:146::/run/uuidd:/usr/sbin/nologin
polkitd:x:998:998:polkit:/nonexistent:/usr/sbin/nologin
systemd-coredump:x:997:997:systemd Core Dumper:/:/usr/sbin/nologin
www-data:x:996:996::/home/www-data:/usr/sbin/nologin
"
